name: Generate preview image

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed
  workflow_dispatch:

env:
  PREVIEW_MARKDOWN_FILE: preview.markdown
  PREVIEW_IMAGE_FILE: assets/image/preview-image.png

jobs:
  check_if_updated:
    runs-on: ubuntu-latest
    outputs:
      skip_generate: ${{ steps.check_preview_updated.outputs.skip_generate }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}
        fetch-depth: 2

    - name: Check if $PREVIEW_MARKDOWN_FILE were updated
      id: check_preview_updated
      run: |
        updated=$(git diff --name-only HEAD~1 HEAD -- $PREVIEW_MARKDOWN_FILE | grep $PREVIEW_MARKDOWN_FILE || true)
        if [ -z "$updated" ]; then
          echo "$PREVIEW_MARKDOWN_FILE was not updated in the last commit."
          echo "skip_generate=1" >> "$GITHUB_OUTPUT"
        else
          echo "skip_generate=0" >> "$GITHUB_OUTPUT"
        fi

  generate_png:
    needs: check_if_updated
    if: ${{ needs.check_if_updated.outputs.skip_generate == '0' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Set up Google Chrome
      if: ${{ needs.check_if_updated.outputs.skip_generate == '0' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Set up Node.js
      if: ${{ needs.check_if_updated.outputs.skip_generate == '0' }}
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Puppeteer
      if: ${{ needs.check_if_updated.outputs.skip_generate == '0' }}
      run: |
        npm install puppeteer

    - name: Generate PNG from URL
      if: ${{ needs.check_if_updated.outputs.skip_generate == '0' }}
      env:
        URL: 'https://spritwo.ch/preview' #${{ secrets.SITE_URL }}
        CHROME_EXECUTABLE_PATH: 'google-chrome-stable'
      run: |
        node .github/workflow-helpers/generate_png.js

    - name: Create and checkout new branch
      if: ${{ needs.check_if_updated.outputs.skip_generate == '0' }}
      run: |
        git checkout -b preview-image-update

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "FabianVolkers@users.noreply.github.com"
        git add $PREVIEW_IMAGE_FILE
        git commit -m "Update $PREVIEW_IMAGE_FILE" || exit 0
        git push origin preview-image-update

    - name: Create pull request
      id: create_pr
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        response=$(curl -s -w "%{http_code}" -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token $GH_TOKEN" "https://api.github.com/repos/${{ github.repository }}/pulls" -d '{"title":"Update preview-image.png with new date","head":"preview-image-update","base":"main","maintainer_can_modify": true}')
        status_code=$(echo "$response" | tail -n1)
        pr_data=$(echo "$response" | head -n-1)
        if [ $status_code -ne 201 ]; then
          echo "Failed to create pull request"
          exit 1
        fi
        pr_id=$(echo "$pr_data" | jq '.number')
        echo "pr_id=$pr_id" >> "$GITHUB_OUTPUT"

    - name: Merge pull request
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        pr_id=${{ steps.create_pr.outputs.pr_id }}
        response=$(curl -s -w "%{http_code}" -X PUT -H "Accept: application/vnd.github+json" -H "Authorization: token $GH_TOKEN" "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_id/merge")
        status_code=$(echo "$response" | tail -n1)
        if [ $status_code -ne 200 ]; then
          echo "Failed to merge pull request"
          exit 1
        fi

    - name: Delete preview-image-update branch
      run: |
        git push origin --delete preview-image-update
